### ISSUE TITLE
Create a better Login screen

### ISSUE THREAD

**Issue by akshuu** [CodePathGrp10/TravelMemo#7]
Low on priority as of now

**Comment by akshuu** [comment]
@traviskim , can we have a solid background to the login layout ?  it is difficult to make it out on the blurred background

**Comment by traviskim** [comment]
@akshuu we dont have a logo, so I think a solid background is too simple. However, I agree that it is difficult to make it out on the blurred background. Thus I made some changes on signin page, so please give me any comment how you feel.

**Comment by akshuu** [comment]
@traviskim looks better. 2 things 
1. Can you get the G+ signin button next to the SignIn button.
2. Can you align the Remember me checkbox iwth the password text field?

**Comment by traviskim** [comment]
@akshuu updated 2 things you mentioned. Let me know if it is what you feel right.

**Comment by akshuu** [comment]
i do not see any checkin's from you.

**Comment by traviskim** [comment]
@akshuu  it looks it did not pushed well.. are you able to see the changes now?

**Comment by akshuu** [comment]
@traviskim  looks good. I changed the size of the button and also some margins around the layouts so that they are more optimzed in terms of drawing. Hope you are ok with that
