### ISSUE TITLE
The parallax effect needs to be more elegant

### ISSUE THREAD

**Issue by akshuu** [CodePathGrp10/TravelMemo#9]
the title text shrinks and then becomes a little bigger.
also the path is curved and not straight up.

**Comment by traviskim** [comment]
1. I made the curve path for animation, but I change to move straight up.
2. I don't know the solution for the title text shrink issue which is bold-normal-bold style change.

**Comment by akshuu** [comment]
oh ok.  i did not know that you did it on purpose..
l haven't seen much apps do the curve transistion and hence i was wondering about it.
